<a href="https://colab.research.google.com/github/hardymunjal/Mathematics-for-ML/blob/main/Lecture-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lecture 1 - Vectors Recap

In [1]:
# Import Packages
import numpy as np

In [2]:
# Initialise a vector
v = np.array([1,-1,2])
w = np.array([2, 5, 2])

In [3]:
# Addition of Vectors
x = v + w
print(x)

[3 4 4]


In [4]:
# Subtraction of vectors
x = v - w
print(x)

[-1 -6  0]


In [5]:
# Scalar Multiplication
x = 2 * v
print(x)

[ 2 -2  4]


In [6]:
# Get magnitude of vector
mag_v = np.linalg.norm(v)
print(mag_v)

2.449489742783178


In [7]:
# Dot Product
x = np.dot(v, w) # returns scalar
print(x)

1
