<a href="https://colab.research.google.com/github/hardymunjal/Mathematics-for-ML/blob/main/Week-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Lecture 1 - Vectors Recap

In [1]:
# Import Packages
import numpy as np

In [2]:
# Initialise a vector
v = np.array([1,-1,2])
w = np.array([2, 5, 2])

In [3]:
# Addition of Vectors
x = v + w
print(x)

[3 4 4]


In [4]:
# Subtraction of vectors
x = v - w
print(x)

[-1 -6  0]


In [5]:
# Scalar Multiplication
x = 2 * v
print(x)

[ 2 -2  4]


In [6]:
# Get magnitude of vector
mag_v = np.linalg.norm(v)
print(mag_v)

2.449489742783178


In [7]:
# Dot Product
x = np.dot(v, w) # returns scalar
print(x)

1


## Lecture 2 - Matrix Recap

In [9]:
# Initialize Matrix
V = np.array([[1,2], [2,3],[4,5]])
print(V)

[[1 2]
 [2 3]
 [4 5]]


In [10]:
W = np.array([[8,9], [6,7],[1,3]])
print(W)

[[8 9]
 [6 7]
 [1 3]]


In [11]:
# Add two matrix
X = np.add(V, W)
print(X)

[[ 9 11]
 [ 8 10]
 [ 5  8]]


In [12]:
# Subtract two matrix
X = np.subtract(V, W)
print(X)

[[-7 -7]
 [-4 -4]
 [ 3  2]]


In [14]:
# Vector Multiplication
P = np.array([[1, 4, 1], [4, 5, 6]])
R = np.array([[1,2], [3,4], [5,6]])
X = np.dot(P, R)
print(X)

[[18 24]
 [49 64]]


In [17]:
# Calculate determinant
det_X = np.linalg.det(X)
print(det_X)

-24.00000000000011


In [19]:
# Calculate Inverse
inv_X = np.linalg.inv(X)
print(inv_X)

[[-2.66666667  1.        ]
 [ 2.04166667 -0.75      ]]
